# Generated by Django 5.2.5 on 2026-01-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='classmodel',
            name='tags',
        ),
        migrations.AddField(
            model_name='classmodel',
            name='tags',
            field=models.ManyToManyField(related_name='classes', to='classes.tag'),
        ),
    ]
