# Generated by Django 5.2.5 on 2026-01-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_tag_remove_classmodel_tags_classmodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='class_type',
            field=models.BooleanField(default=True),
        ),
    ]
