# Generated by Django 5.2.5 on 2026-01-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_classmodel_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='class_type',
            field=models.BooleanField(),
        ),
    ]
