# Generated by Django 5.2.5 on 2026-01-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_classmodel_class_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmodel',
            name='class_type',
        ),
    ]
