# Generated by Django 5.2.5 on 2026-01-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_remove_question_course_alter_question_option_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
