# Generated by Django 5.2.5 on 2026-01-12 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_question_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='lectures/videos/')),
                ('file_1', models.FileField(blank=True, null=True, upload_to='lectures/docs/')),
                ('file_2', models.FileField(blank=True, null=True, upload_to='lectures/docs/')),
                ('file_3', models.FileField(blank=True, null=True, upload_to='lectures/docs/')),
                ('file_4', models.FileField(blank=True, null=True, upload_to='lectures/docs/')),
                ('file_5', models.FileField(blank=True, null=True, upload_to='lectures/docs/')),
                ('external_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='classes.classmodel')),
            ],
        ),
    ]
