# Generated by Django 5.2.5 on 2026-01-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_submitquiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='due_date',
        ),
        migrations.AddField(
            model_name='quiz',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
